<?php

$sessaoUsuario = new Zend_Session_Namespace('USUARIO');

if(isset($sessaoUsuario->idUsuario)) {
  $permissao = $sessaoUsuario->Permissao; 
}

?>

<!-- HOME -->
<a
	href="<?php echo $this->url(array('controller'=>'noticias',
'action'=>'index'));?>"
	class="classe2">HOME</a>
<!-- VEï¿½CULO -->

<a
	href="<?php echo $this->url(array('controller'=>'veiculo',
'action'=>'veiculo'));?>"
	class="classe2">VEÍCULO</a>
<!-- USUï¿½RIOS -->
<a
	href="<?php echo $this->url(array('controller'=>'usuario',
'action'=>'usuario'));?>"
	class="classe2">USUÁRIO</a>

<!-- MARCA -->
<a
	href="<?php echo $this->url(array('controller'=>'marca',
'action'=>'marca'));?>"
	class="classe2">MARCA</a>

<!-- MODELO -->
<a
	href="<?php echo $this->url(array('controller'=>'modelo',
'action'=>'modelo'));?>"
	class="classe2">MODELO</a>

<!-- CATEGORIA -->
<a
	href="<?php echo $this->url(array('controller'=>'categoria',
'action'=>'categoria'));?>"
	class="classe2">CATEGORIA</a>
<!-- CLIENTES -->
<a
	href="<?php echo $this->url(array('controller'=>'cliente',
'action'=>'cliente'));?>"
	class="classe2">CLIENTES</a>


<a
	href="<?php echo $this->url(array('controller' => 'cargo',
        'action' => 'cargo'));?>"
	class="classe2">CARGO</a>


<!-- VENDAS -->
<a
	href="<?php echo $this->url(array('controller'=>'venda',
'action'=>'venda'));?>"
	class="classe2">VENDA</a>

<!-- EMPREGADOS -->

<a
	href="<?php echo $this->url(array('controller'=>'empregado',
'action'=>'empregado'));?>"
	class="classe2">EMPREGADO</a><br /><br />

<!-- gastos do veiculo -->
<a
	href="<?php echo $this->url(array('controller'=>'gastosveiculo',
'action'=>'gastosveiculo'));?>"
	class="classe3">GASTOS VEÍCULO</a>


<!-- GASTOS DA EMPRESA -->
<a
	href="<?php echo $this->url(array('controller'=>'gastosempresa',
'action'=>'gastosempresa'));?>"
	class="classe3">GASTOS EMPRESA</a>

<!-- VISUALIZA GASTOS -->
<a
	href="<?php echo $this->url(array('controller'=>'visualizagastos',
'action'=>'visualizagastos'));?>"
	class="classe3">VISUALIZAR GASTOS</a>


<!-- FATUARMENTO -->
<a
	href="<?php echo $this->url(array('controller'=>'faturamento',
'action'=>'faturamento'));?>"
	class="classe3">FATURAMENTO</a>

<!-- COMISSÃO -->
<a
	href="<?php echo $this->url(array('controller'=>'comissao',
'action'=>'comissao'));?>"
	class="classe3">COMISSÃO</a>
	


<!-- SAIR -->
<a
	href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'), null, true); ?>"
	class="classe3">SAIR </a>




<h1>VEÍCULOS</h1>
<?php if($permissao == 1 || $permissao == 3 || $permissao == 4){ ?> 

<table border='1' width="80%">
	<tr>
		<th>Placa</th>
		<th>Cor</th>
		<th>Quantidade Portas</th>
		<th>Itens Opcionais</th>
		<th>Valor Pago</th>
		<th>Valor Venda</th>
		<th>Total Ganho</th>
		<th>Ano Modelo</th>
		<th>Ano Fabricação</th>
		<th>Combustível</th>
		<th>Estado de Uso</th>
		<th>Status</th>
		<th>Editar</th>
		<th>Excluir</th>
	</tr>



	<?php foreach ($this->veiculo as $veiculo) : ?>
	<tr>
		<td width="70%"><?php echo $this->escape($veiculo->Placa); ?></td>
		<td><?php echo $this->escape($veiculo->Cor); ?></td>
		<td><?php echo $this->escape($veiculo->NroPortas); ?></td>
		<td><?php echo $this->escape($veiculo->ItensOpcionais); ?></td>
		<td><?php echo $this->escape($veiculo->ValorPago); ?></td>
		<td><?php echo $this->escape($veiculo->ValorVenda); ?></td>
		<td><?php echo $this->escape($veiculo->TotalGanho); ?> </td>
		<td><?php echo $this->escape($veiculo->AnoModelo); ?></td>
		<td><?php echo $this->escape($veiculo->AnoFabricacao); ?></td>

		<?php if ($this->escape($veiculo->Combustivel) == 1){ ?>
		<td>Gasolina</td>
		<?php } if ($this->escape($veiculo->Combustivel) == 2){ ?>
		<td>Alcool</td>
		<?php } if ($this->escape($veiculo->Combustivel) == 3){ ?>
		<td>Total Flex</td>
		<?php }  ?>


		<?php if ($this->escape($veiculo->EstadoDeUso) == 1){ ?>
		<td>Novo</td>
		<?php } if ($this->escape($veiculo->EstadoDeUso) == 2){ ?>
		<td>Semi-Novo</td>
		<?php } if ($this->escape($veiculo->EstadoDeUso) == 3){ ?>
		<td>Usado</td>
		<?php }  ?>



		<?php if ($this->escape($veiculo->Status) == 1){ ?>
		<td>Vendido</td>
		<?php } if ($this->escape($veiculo->Status) == 2){ ?>
		<td>Disponível</td>
		<?php }  ?>


		<td><a
			href="<?php echo $this->url(array('controller' => 'veiculo',
        'action' => 'editveiculo', 'idVeiculo' => $veiculo->idVeiculo));
    ?>">EDITAR</a></td>
		<td><a
			href="<?php echo $this->url(array('controller' => 'veiculo',
        'action' => 'deleteveiculo', 'idVeiculo' => $veiculo->idVeiculo));
    ?>">EXCLUIR</a></td>
	</tr>
	<?php endforeach; ?>
</table>

<a
	href="<?php echo $this->url(array('controller'=>'veiculo',
'action'=>'addveicu'));?>" class="adicionar">ADICIONAR</a>


<?php }else{ ?>


    <p>Desculpe, mas voce nao tem permissão para acessar essa sessão <br></br>
   <a
	href="<?php echo $this->url(array('controller'=>'noticias',
'action'=>'index'));?>">Clique aqui</a> para voltar ao menu 
	</p>
<?php } ?>
