<?php


//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=UTF-8');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=iso8859-1');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Sistema Carrao');
echo $this->doctype(); ?>
<html>
<head>

<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/script.js"></script>
<!--<?php echo $this->jQuery(); ?>-->
</head>
<body>
<div id="tudo"></div>
<div id="pagina">
<h1><?php echo $this->escape($this->title); ?></h1>
<?php echo $this->layout()->content; ?></div>



<div id="rodape"></div>

</body>
</html>
